version: "2"
linters:
  settings:
    errcheck:
      exclude-functions:
        - (hash.Hash).Write
        - (*testing.T).Fatalf
        - (*testing.T).Errorf
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - _examples
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
