package openssl

/*
#include <openssl/evp.h>
#include <openssl/crypto.h>
*/
import "C"
import (
	"runtime"
	"strings"
)

// KeyHandle is an opaque wrapper around *C.EVP_PKEY that can be safely
// referenced from outside the openssl package (C types cannot cross
// Go package boundaries). All key operations accept a *KeyHandle.
type KeyHandle struct {
	pkey *C.EVP_PKEY
}

// NewKeyHandle wraps a raw EVP_PKEY pointer in a KeyHandle.
// A finalizer is set as a safety net, but callers should explicitly
// call Free or Zeroize to release resources deterministically.
func NewKeyHandle(pkey *C.EVP_PKEY) *KeyHandle {
	h := &KeyHandle{pkey: pkey}
	runtime.SetFinalizer(h, (*KeyHandle).finalize)
	return h
}

// Free releases the underlying EVP_PKEY. Safe to call multiple times.
func (h *KeyHandle) Free() {
	if h.pkey != nil {
		runtime.SetFinalizer(h, nil)
		C.EVP_PKEY_free(h.pkey)
		h.pkey = nil
	}
}

// IsNil returns true if the handle has been freed or was never set.
func (h *KeyHandle) IsNil() bool {
	return h == nil || h.pkey == nil
}

// finalize is the GC safety net. Users must call Free explicitly.
func (h *KeyHandle) finalize() {
	if h.pkey != nil {
		C.EVP_PKEY_free(h.pkey)
		h.pkey = nil
	}
}

// --- Functions that operate on KeyHandle ---

// GenerateGOSTKeyHandle generates a GOST key pair and returns a KeyHandle.
func GenerateGOSTKeyHandle(signNID int, curveOID string) (*KeyHandle, error) {
	pkey, err := GenerateGOSTKey(signNID, curveOID)
	if err != nil {
		return nil, err
	}
	return NewKeyHandle(pkey), nil
}

// LoadGOSTPrivKeyHandle creates a GOST key from raw private key bytes
// and returns a KeyHandle.
func LoadGOSTPrivKeyHandle(signNID int, curveOID string, raw []byte) (*KeyHandle, error) {
	pkey, err := LoadGOSTPrivKey(signNID, curveOID, raw)
	if err != nil {
		return nil, err
	}
	return NewKeyHandle(pkey), nil
}

// ExtractRawPrivKeyH extracts the raw private key bytes from a KeyHandle.
func ExtractRawPrivKeyH(h *KeyHandle, keySize int) ([]byte, error) {
	if h.IsNil() {
		return nil, &OpenSSLError{Op: "ExtractRawPrivKeyH", Text: "nil key handle"}
	}
	return ExtractRawPrivKey(h.pkey, keySize)
}

// ExtractRawPubKeyH extracts the raw/SPKI public key bytes from a KeyHandle.
func ExtractRawPubKeyH(h *KeyHandle) ([]byte, error) {
	if h.IsNil() {
		return nil, &OpenSSLError{Op: "ExtractRawPubKeyH", Text: "nil key handle"}
	}
	return ExtractRawPubKey(h.pkey)
}

// SignDigestH signs a pre-computed digest using a KeyHandle.
func SignDigestH(h *KeyHandle, digest []byte) ([]byte, error) {
	if h.IsNil() {
		return nil, &OpenSSLError{Op: "SignDigestH", Text: "nil key handle"}
	}
	return SignDigest(h.pkey, digest)
}

// VerifyDigestH verifies a signature over a pre-computed digest using a KeyHandle.
func VerifyDigestH(h *KeyHandle, digest, sig []byte) (bool, error) {
	if h.IsNil() {
		return false, &OpenSSLError{Op: "VerifyDigestH", Text: "nil key handle"}
	}
	return VerifyDigest(h.pkey, digest, sig)
}

// ValidatePublicKeyH runs EVP_PKEY_param_check and EVP_PKEY_public_check on a KeyHandle.
//
// gost-engine does not implement the EVP_PKEY check operations for GOST key types,
// so "operation not supported for this keytype" is treated as a successful validation.
// Keys generated by gost-engine are valid by construction.
func ValidatePublicKeyH(h *KeyHandle) error {
	err := ValidatePublicKey(h.pkey)
	if err == nil {
		return nil
	}
	// gost-engine returns "operation not supported for this keytype" because
	// it does not implement the keymgmt check callback. This is expected.
	if e, ok := err.(*OpenSSLError); ok {
		if strings.Contains(e.Text, "not supported for this keytype") {
			return nil
		}
	}
	return err
}
